### ISSUE TITLE
initial version

### ISSUE THREAD

**Issue by alessioalex** [kdzwinel/betwixt#1]
hey @kdzwinel we spoke on reddit yesterday. I would like to help out. Can you put a raw version of the project on a separate branch so I can have a look at in this stage? cheers!

**Comment by kdzwinel** [comment]
Your help will be extremely appreciated! My plan is to release it on November 21st, sorry that you have to wait :( Ping me on hangouts/gmail and I'll share the details.

**Comment by koresar** [comment]
I'd love to give it a test. Ping me if you need any testers. Cheers

**Comment by kdzwinel** [comment]
@alessioalex @koresar I released it yesterday :fireworks: ,your help will be much appreciated!

**Comment by samccone** [comment]
:bow:
