### ISSUE TITLE
Project Icon / Logo

### ISSUE THREAD

**Issue by kdzwinel** [kdzwinel/betwixt#18]
Since we are going to have installable bundles, let's add some reasonable icon.

https://www.google.com/design/icons/ + some nice gradients?

**Comment by c0b41** [comment]
I think it's pretty cool [Flash İcon](https://www.iconfinder.com/icons/631544/earth_flash_hero_man_saver_super_superhero_icon#size=512)

**Comment by kdzwinel** [comment]
Thanks for proposition! I'm not sure though if ⚡is something Betwixt should stick to. That thunderbolt was chosen randomly and never made much sense.

I've been playing with some icons and ended up creating this:
![betwixt_logo_color_trans](https://cloud.githubusercontent.com/assets/985504/11616372/6a952bbe-9c79-11e5-8e73-d3e03caacb1f.png)

WDYT?

xcf is available [here](https://dl.dropboxusercontent.com/u/8989748/betwixt_logo.xcf) if anyone wants to play with it.

**Comment by kdzwinel** [comment]
And couple more:

![betwixt_logo_](https://cloud.githubusercontent.com/assets/985504/11638980/2995ed18-9d2a-11e5-9a54-8d58832004d7.png)
![betwixt_logo_record](https://cloud.githubusercontent.com/assets/985504/11638982/29b07e4e-9d2a-11e5-8f44-addf85d9294f.png)
![betwixt_logo_pirate](https://cloud.githubusercontent.com/assets/985504/11638981/29989b8a-9d2a-11e5-87b1-e60922503aa3.png)

**Comment by kdzwinel** [comment]
Latest iteration:

![betwixt_box_ink_g](https://cloud.githubusercontent.com/assets/985504/12076945/2b60cf88-b1c4-11e5-8376-0b577055205b.png)

**Comment by c0b41** [comment]
@kdzwinel I think this logo pretty cool, and all size convert them https://cloudup.com/c29Q-ML9ohp

**Comment by kdzwinel** [comment]
Logo from [my comment above](https://github.com/kdzwinel/betwixt/issues/18#issuecomment-168449595) will be the official one. Now I need to figure out how to make an icon based on it - if anyone can help, please do.

**Comment by kdzwinel** [comment]
And I finally got some time to play with inkscape and create the icon:

![betwixt_icon](https://cloud.githubusercontent.com/assets/985504/14296376/1de1dc94-fb7a-11e5-98d4-03aa5aae95b3.png)

**Comment by kdzwinel** [comment]
And a preview of how it looks on osx:

<img width="170" alt="screen shot 2016-04-06 at 09 40 48" src="https://cloud.githubusercontent.com/assets/985504/14309281/b5f7873e-fbdb-11e5-9a21-dc1912db65ef.png">

and windows (pixelated because I'm using a VM):
<img width="97" alt="betwixt-window-task" src="https://cloud.githubusercontent.com/assets/985504/14311824/a352ea48-fbe9-11e5-9a14-2ee2148c7d71.png">
<img width="256" alt="betwixt-windows" src="https://cloud.githubusercontent.com/assets/985504/14311839/bbcbac7c-fbe9-11e5-82ca-e46dd9f8bbb4.png">

**Comment by kdzwinel** [comment]
Fixed via https://github.com/kdzwinel/betwixt/commit/514a5a391355ad632c3a05baf451fc465649f118
