### ISSUE TITLE
nothing gets captured

### ISSUE THREAD

**Issue by zinking** [kdzwinel/betwixt#20]
after started and setting the proxy. I get nothing captured. 

log screen is filled with `FEConnection error: Connection not ready, message not sent.`

I am using the node 5.1 on macosx

**Comment by kdzwinel** [comment]
I've seen that happen to me. Backend (node script) is not able to connect with the frontend (devtools). It tries to do so via localhost:1337, maybe this port is blocked on your machine?

In the future, we probably should get rid of websocket connection all together and use internal electron communication.

**Comment by dgospodarets** [comment]
Hey @kdzwinel are you applying Web Proxy after betwixt has been started?

**Comment by kdzwinel** [comment]
hey @dgospodarets - the issue that @zinking has is not related with the proxy, it's related with communication between front-end (devtools) and back-end(node). It will be fixed via #23. Are you seeing the same issue?

Proxy starts as soon as app starts. It does so on port 8008. It doesn't meter (from what I've tested) when you set the proxy in the system settings (at least on OSX).

**Comment by shospodarets** [comment]
@kdzwinel yep, I'm seeing the same issue.
Works only when Web Proxy is activated after starting betwixt

**Comment by kdzwinel** [comment]
ok, I'm moving this discussion to #24 as it's different than error reported by OP.

@malyw @damoonrashidi please provide more details in #24 .

**Comment by kdzwinel** [comment]
@zinking this should be fixed now, backend and frontend no longer use websocket to talk to each other.
