### ISSUE TITLE
betwixt modify http header format

### ISSUE THREAD

**Issue by fants** [kdzwinel/betwixt#27]
my response http header：

> set-cookie:dsid=EfhrHh; expires=Fri, 04-Dec-2015 03:43:54 GMT; Max-Age=86400; path=/
> set-cookie:dlastact=1449114234; expires=Fri, 04-Dec-2015 03:43:54 GMT; Max-Age=86400; path=/
> set-cookie:dreg=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
> set-cookie:dcloudstatpost=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/

after betwixt proxy:

> set-cookie:dsid=EfhrHh; expires=Fri, 04-Dec-2015 03:43:54 GMT; Max-Age=86400; path=/dlastact=1449114234; expires=Fri, 04-Dec-2015 03:43:54 GMT; Max-Age=86400; path=/dreg=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/dcloudstatpost=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/

So the cookie does not work

**Comment by kdzwinel** [comment]
Thanks for reporting. I suspect it's a `http-proxy` package issue as betwixt itself doesn't modify responses. I'll try to debug that.

**Comment by kdzwinel** [comment]
Turns out it was my error. It's fixed now, thanks again for reporting.
