### ISSUE TITLE
Request payload not shown

### ISSUE THREAD

**Issue by mhnagaoka** [kdzwinel/betwixt#28]
Unlike Chrome DevTools, a request payload / form data is not shown on the detail pane.

![image](https://cloud.githubusercontent.com/assets/903837/11830468/a94babf2-a38c-11e5-8811-a85afdb28868.png)

For reference, this is a Chrome's screenshot of a similar request made with Postman. Notice the "Form Data" section at the bottom of the screenshot.

![image](https://cloud.githubusercontent.com/assets/903837/11830538/51bca048-a38d-11e5-89e8-192453ac9a25.png)

**Comment by kdzwinel** [comment]
Good catch, thanks! I've fixed it in #30 - please take a look.

**Comment by homburg** [comment]
Great, works for me :+1:

**Comment by kdzwinel** [comment]
Thanks for testing @homburg! I'm merging this.

**Comment by mhnagaoka** [comment]
Great! Thanks a lot! :smile:
