### ISSUE TITLE
Downloading electron-v0.34.5-darwin-x64.zip is too slow when i npm install. Can i download it alone?

### ISSUE THREAD

**Issue by deju** [kdzwinel/betwixt#37]
When i exec npm install, it is slow to download electron-v0.34.5-darwin-x64.zip. Can i download it alone?

**Comment by kdzwinel** [comment]
Electron is an integral part of this app, you can't skip it.

Consider downloading one of available Betwixt builds: https://github.com/kdzwinel/betwixt/releases - that's the most time-efficient way of getting the app.

**Comment by desenmeng** [comment]
@deju   you can use  [cnpm](http://cnpmjs.org/) in China

**Comment by deju** [comment]
@demohi Done! Thanks.

**Comment by doc-han** [comment]
How was the cnpm used to solve this? need Help
