### ISSUE TITLE
sorry it doesnot work

### ISSUE THREAD

**Issue by willshion** [kdzwinel/betwixt#44]
win 64  it just empty nothing go on 
i did used poxy setting as you said.

**Comment by willshion** [comment]
i imaged that would be  ,but you make it ture .

**Comment by kdzwinel** [comment]
windows 10 64-bit? Betwixt window is absolutely empty or you are not recording any requests?

**Comment by kdzwinel** [comment]
Closing due to lack of sufficient info to investigate. Let me know if you'll need help.
