### ISSUE TITLE
Why not use Template instead of js DOM? 

### ISSUE THREAD

**Issue by fwon** [kdzwinel/betwixt#46]
I confused that why not using Template to create the Interface, not js DOM (create DOM in js).
Also i saw vscode source code don't use HTML too.
How does author consider for that?

**Comment by kdzwinel** [comment]
Hey!

I'm not sure what do you mean exactly, but that's also not the place to ask this question - try StackOverflow or maybe Chromium dev slack ( https://chromiumdev-slack.herokuapp.com/ ). Betwixt interface is built on the top of Chrome DevTools, I haven't built the UI.
