### ISSUE TITLE
Remove unnecessary UI elements

### ISSUE THREAD

**Issue by kdzwinel** [kdzwinel/betwixt#5]
Some UI elements do not work and do not make sense.
This requires digging into the DevTools code.

Things to remove:
- [x] preserve log
- [x] disable cache
- [x] capture screenshots
- [x] "Clear browser cache" - context menu
- [x] "Clear browser cookies" - context menu
- [x] hide data URLs

**Comment by samccone** [comment]
right now as we were talking about this is going to be a hack job into dev tools, would be nice to be able to programmatically disable these features in devtools ... however this might just add too much noise to devtools to enable this functionality so a patch commit that we can manually apply will prob be best here 

cc @paulirish

**Comment by paulirish** [comment]
konrad, you're speaking the protocol into the frontend? 

well actually

based on the animation it appears that you're already hacking the frontend. so applying some `display:none`'s is easy. and context menu.... iunno that will be harder. :)

**Comment by kdzwinel** [comment]
I kinda hoped that I'll keep DT easy to update by relying on config files as much as possible (this worked out for the main tabs). However, as Sam mentioned, it looks like it will be ~~impossible~~ very hard going forward. Anyway, I still want to check what's possible to turn off using config files, for everything else, we'll do the `display:none` thing.

> konrad, you're speaking the protocol into the frontend?

do I use remote debugging protocol to communicate with the frontend? if so :arrow_right:  yes.
